### ISSUE TITLE
[feature]: Shipping form fields shown as not required (UI), whereas they are from the code

### ISSUE THREAD

**Issue by vasilii-b** [magento/pwa-studio#2204] opened 2020-03-03 08:27 UTC
**Describe the bug**
The shipping form fields are not visually required at first glance. They are actually required from the codebase and this is told to the customer after he/she presses the "Use Address" button.

**To reproduce**
1. Go to a product page
2. Add the product to the cart
3. Open the cart
4. Click on the "Checkout" button
5. Press the button to add the shipping information
6. _See that field labels does not contain any hint that they are required_
7. Press the "Use address" button
8. _See error messages that there are required fields not filled in_

![shipping-form-fields-not-inform-that-are-required](https://user-images.githubusercontent.com/13456702/75756445-593e5e00-5d39-11ea-848b-6c657f72970c.jpg)

**Expected behavior**
Each required form field should inform beforehand that it is required.
![shipping-form-fields-has-required-symbol](https://user-images.githubusercontent.com/13456702/75756172-d9b08f00-5d38-11ea-9706-d05ec7bcee7f.jpg)

**Screenshots**

**Additional context**
N/A

**Possible solutions**
N/A

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: any
 - OS [e.g. iOS8.1, Windows 10]: any
 - Browser [e.g. Chrome, Safari]: any
 - Browser Version [e.g. 22]: any
 - Magento Version: any
 - PWA Studio Version: 
 - NPM version `npm -v`: 6.9.0
 - Node Version `node -v`: 10.16.3

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by Jordaneisenburger** [comment] 2020-03-03 09:04
@vasilii-b there is a new cart page in the works. So I'm pretty sure the drawer functionality will be obsolete very soon. Unfortunately Github is not very up-to-date at the moment. @sirugh Do you have a status on the development for the cart page ?

**Comment by awilcoxa** [comment] 2020-03-09 16:07
Removed bug label as the feature is working as designed. Initial design did not include a specific required field flag/indicator since all of the fields in the checkout flow are currently required. 

@soumya-ashok tagging for UX review since there is a use case in a more complex checkout flow where there is some X% of required vs optional fields that would make sense to clearly delineate between required/optional

**Comment by tjwiebell** [comment] 2020-06-09 14:56
Closing this out as expected UI. I believe @soumya-ashok wanted to provide some justification for our design choice, which will be provided here soon.

**Closed by tjwiebell** 2020-06-09 14:56 UTC
Labels: Progress: PR created, needs-ux
