### ISSUE TITLE
[bug]: Pdf files stored in media folder is not accesable via pwa (redirect to 404)

### ISSUE THREAD

**Issue by SerMedvid** [magento/pwa-studio#3966] opened 2022-09-30 06:23 UTC
**Describe the bug**

Website can have information stored in pdf files (product instructions, promo data, terms and conditions).
But pdf files stored in "media" folder are not accessible using direct links via the front. The request is forwarded to backend 404.
Media requests are handled via VeniaProxy and I was unable to find any file restrictions for it.
Direct links work with backend URL with no issue. So most probably the issue is in proxy.

**To reproduce**

1. Upload pdf file to any media folders
2. Try to access this file via navigation bar (like https://frontend-url.com/media/pdf/1.pdf)
3. See 404 redirect

**Expected behavior**

Pdf file is opened/downloaded from the browser window

**Please complete the following device information:**

-   Device PC:
-   Browser Chrome
-   Magento Version Adobe Community 2.4.4
-   Magento PWA Studio 12.4.0

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [X] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment] 2022-10-03 14:17
@adobe export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment] 2023-07-05 07:46
Hi @SerMedvid We are not able to reproduce this issue. Attached is the screenshot for the same 

<img width="1439" alt="Screenshot 2023-07-05 at 1 14 37 PM" src="https://github.com/magento/pwa-studio/assets/97873570/e9087aeb-c3a8-41e4-b42a-0c1c990544a1">

Please let us know if we are missing any point.

**Comment by glo82145** [comment] 2023-07-26 06:05
As we have not got any update on this, hence we are closing it. Please feel free to reopen in case of any update.

**Closed by glo82145** 2023-07-26 06:05 UTC
Labels: bug, help wanted, triage-done, Issue: Needs Update, issue: Cannot Reproduce
