### ISSUE TITLE
[bug]: Error: Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'

### ISSUE THREAD

**Issue by LucasCalazans** [magento/pwa-studio#3434] opened 2021-09-22 13:05 UTC
**Describe the bug**

I'm receiving the following error when I try to run `yarn watch` after the scaffolding command

```
me:~/pwa-studio$ yarn watch
yarn run v1.22.11
$ webpack-dev-server --progress --color --env.mode development
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'
Require stack:
- pwa-studio/node_modules/workbox-webpack-plugin/build/generate-sw.js
- pwa-studio/node_modules/workbox-webpack-plugin/build/index.js
- pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/plugins/ServiceWorkerPlugin.js
- pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/configureWebpack/getClientConfig.js
- pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/configureWebpack/configureWebpack.js
- pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/configureWebpack/index.js
- pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/index.js
- pwa-studio/node_modules/@magento/pwa-buildpack/lib/index.js
- pwa-studio/webpack.config.js
- pwa-studio/node_modules/webpack-cli/bin/convert-argv.js
- pwa-studio/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (pwa-studio/node_modules/workbox-webpack-plugin/build/generate-sw.js:20:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (pwa-studio/node_modules/workbox-webpack-plugin/build/index.js:10:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'pwa-studio/node_modules/workbox-webpack-plugin/build/generate-sw.js',
    'pwa-studio/node_modules/workbox-webpack-plugin/build/index.js',
    'pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/plugins/ServiceWorkerPlugin.js',
    'pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/configureWebpack/getClientConfig.js',
    'pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/configureWebpack/configureWebpack.js',
    'pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/configureWebpack/index.js',
    'pwa-studio/node_modules/@magento/pwa-buildpack/lib/WebpackTools/index.js',
    'pwa-studio/node_modules/@magento/pwa-buildpack/lib/index.js',
    'pwa-studio/webpack.config.js',
    'pwa-studio/node_modules/webpack-cli/bin/convert-argv.js',
    'pwa-studio/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Related Issue**

#3339

**To reproduce**

1. Run `yarn create @magento/pwa` with all the default answers
2. `cd <project-folder>
3. `yarn buildpack create-custom-origin .`
4. `yarn watch`
5. See the error

**Expected behavior**

The application should be run after the `yarn watch` command

**Please complete the following device information:**

-   Device: PC, Windows 10
-   Browser: CLI

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [x] `create-pwa`

**Comment by sermagnus** [comment] 2021-10-30 16:30
I confirm the problem, encountered today launching the yarn create command

It can be fixed with:
`yarn add workbox-webpack-plugin`

**Comment by MinhOmega** [comment] 2022-03-02 10:32
Any luck here, even i run 
`yarn add workbox-webpack-plugin -W`
It still get this errors

**Comment by donqric** [comment] 2022-06-07 12:48
Here to report that this also might happen when running `npm install` rather than `yarn install` beforehand

**Comment by RaghavendraTirumalasetti** [comment] 2023-05-18 10:25
Hi @LucasCalazans,

As per retesting the issue we are not able to reproduce it and working fine.

Followed steps to reproduce :
1. Run yarn create @magento/pwa with all the default answers
2. `cd
3. yarn buildpack create-custom-origin .
4. yarn watch
5. See the error

Note: Kindly let us know if we are missing any step to reproduce on above. So that we can proceed further to reproduce the issue else will close it.

**Comment by glo82145** [comment] 2023-06-06 10:09
We waited for more than 14 days for update on this issue, hence we are closing it. 

Please feel free to reopen if you are still have any update on the same.

**Closed by glo82145** 2023-06-06 10:10 UTC
Labels: bug, Issue: Needs Update
