### ISSUE TITLE
[bug]: Pagination div active it's outside

### ISSUE THREAD

**Issue by RicardoHds** [magento/pwa-studio#2296] opened 2020-03-31 00:58 UTC
**Describe the bug**
Pagination component add an div when current page it's active, but the number it's outside of this div. 

**To reproduce**
All paginator shows the same error.

**Expected behavior**
For a better manipulation the number should be inside of div with the classname "title.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/30476148/77975743-29db2c80-72b8-11ea-8b0c-7f88f52a622a.PNG)

**Additional context**

**Possible solutions**
Get number like a prop inside of marker div.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
-  `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by LucasCalazans** [comment] 2020-04-04 23:16
@RicardoHds I could not reproduce this issue.

![image](https://user-images.githubusercontent.com/21162174/78463238-e8c88b00-76b0-11ea-9641-9da041cb8cd2.png)
![image](https://user-images.githubusercontent.com/21162174/78463243-f4b44d00-76b0-11ea-9594-3ba0671cae54.png)

I'm running a clone of this repository.

Is it in the category page or in another one?

**Comment by awilcoxa** [comment] 2020-04-07 16:14
created in Jira backlog for triage.

**Comment by awilcoxa** [comment] 2020-04-09 20:49
This issue should be resolved in latest develop

**Comment by awilcoxa** [comment] 2020-04-09 20:50
Closing as resolved

**Closed** 2020-04-09 20:50 UTC
Labels: bug

**Comment by awilcoxa** [comment] 2020-04-09 21:04
fixed in: https://github.com/magento/pwa-studio/pull/2272
