### ISSUE TITLE
webpack issue when yarn run build 

### ISSUE THREAD

**Issue by WaqasMumtaz** [magento/pwa-studio#2009] opened 2019-11-29 12:15 UTC
ERROR in (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1
    Module not found: Error: Can't resolve './..
                                                enia-uilibRootComponentsCMSindex.js' in 'C:\xampp\htdocs\magento\pwa-studio\packages\venia-concept'
     @ (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1 5:71-177
     @ multi (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js

    ERROR in (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1
    Module not found: Error: Can't resolve './..
                                                enia-uilibRootComponentsCategoryindex.js' in 'C:\xampp\htdocs\magento\pwa-studio\packages\venia-concept'
     @ (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1 6:32-143
     @ multi (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js

    ERROR in (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1
    Module not found: Error: Can't resolve './..
                                                enia-uilibRootComponentsNotFoundindex.js' in 'C:\xampp\htdocs\magento\pwa-studio\packages\venia-concept'
     @ (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1 7:32-143
     @ multi (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js

    ERROR in (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1
    Module not found: Error: Can't resolve './..
                                                enia-uilibRootComponentsProductindex.js' in 'C:\xampp\htdocs\magento\pwa-studio\packages\venia-concept'
     @ (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1 8:31-140
     @ multi (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js

    ERROR in (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1
    Module not found: Error: Can't resolve './..
                                                enia-uilibRootComponentsSearchindex.js' in 'C:\xampp\htdocs\magento\pwa-studio\packages\venia-concept'
     @ (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1 9:30-137
     @ multi (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js

**Comment by NamCt1191995** [comment] 2019-12-02 14:02
`enia-uilibRootComponentsCMSindex.js`.
Seems like you are missing path separator `/`. I suggest you checking folder structure.

**Comment by awilcoxa** [comment] 2019-12-12 20:37
closing this issue, @WaqasMumtaz if you're still having the issue feel free to post with detailed info to our community slack channel.

**Closed by awilcoxa** 2019-12-12 20:37 UTC

**Comment by sirugh** [comment] 2019-12-12 21:24
For additional context, it looks like you're trying to run PWA Studio on a windows machine, which we don't currently support.

**Comment by WaqasMumtaz** [comment] 2019-12-26 09:56
> `enia-uilibRootComponentsCMSindex.js`.
> Seems like you are missing path separator `/`. I suggest you checking folder structure.

Please give me some idea how to i build structure project i mean some example ?

**Comment by subhastak** [comment] 2020-01-08 08:08
I have the same issue in windows. Is there any solution for this?

**Comment by subhastak** [comment] 2020-01-10 10:06
> For additional context, it looks like you're trying to run PWA Studio on a windows machine, which we don't currently support.

Dear sirugh, have you come up with a solution to this? Please share.

**Comment by clarah31** [comment] 2020-02-14 12:27
Is there a solution to the problem?
I can't find a file called 
./..enia-uilibRootComponentsCMSindex.js

**Comment by amitmaurya1024** [comment] 2021-09-16 16:45
> Is there a solution to the problem?
> I can't find a file called
> ./..enia-uilibRootComponentsCMSindex.js

did you solve this problem ?

**Comment by amitmaurya1024** [comment] 2021-09-17 05:51
**magento/pwa-studio/blob/v8.0.0/packages/pwa-buildpack/lib/WebpackTools/plugins/RootComponentsPlugin.js#L168-L168 6**

`)}')}`;`

replace with following line

`).replace(/\\/g, '/')}')}`;`

**Comment by narayansinghjai** [comment] 2022-12-02 05:49
hi @amitmaurya1024 

I'm facing this issue  when i run this cmd   "yarn run watch:venia" in windows

Emitting no ServiceWorker in development mode.
i ｢wdm｣: wait until bundle finished: 
i ｢wds｣: Project is running at http://0.0.0.0:10000/
i ｢wds｣: webpack output is served from /
17% [0] building 60/65 modules 5 active C:\Users\jai.narayan\eclipse-workspace\PWA\pwa\pwa-studio\node_modules\html-entities\lib\index.js        
warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
× ｢wdm｣: Child client-config:
       2116 modules

    ERROR in ../pwa-buildpack/node_modules/webpack-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-2
    Module not found: Error: Can't resolve 'C:Usersjai.narayaneclipse-workspacePWApwapwa-studiopackages♂enia-concepten_US.json' in 'C:\Users\jai.narayan\eclipse-workspace\PWA\pwa\pwa-studio\packages\venia-concept'
i ｢wdm｣: Failed to compile.

**Comment by DallogFheir** [comment] 2023-07-25 14:31
@narayansinghjai I don't know if you still need this, but the problem is that `pwa-buildpack` generates a string with unescaped backslashes on Windows. To fix this, you need to replace a single backslash with two backslashes in files _RootComponentsPlugin.js_ and _LocalizationPlugin.js_ in _node_modules\\@magento\pwa-buildpack\lib\WebpackTools\plugins_. I created a [gist](https://gist.github.com/DallogFheir/b7adb74afe41fac647c5b3d501b1cf8a) with code you can copy.
