### ISSUE TITLE
[bug]: Image placeholder height gets overriden by tailwind preflight styles

### ISSUE THREAD

**Issue by TMNRokas** [magento/pwa-studio#3737] opened 2022-03-14 17:36 UTC
**Describe the bug**

Placeholder of Image component is supposed to have a specific height, but it gets overridden by global img rule:
node_modules/tailwindcss/lib/plugins/css/preflight.css
Line: 247
`img,
video {
  max-width: 100%;
  height: auto;
}`

Above rule overrides height that is supposed to be set by attribute in:
node_modules/@magento/venia-ui/lib/components/Image/image.js
`height={talonResourceHeight}`

Since HTML attribute _height_ has lower specificity than a rule from stylesheet, it gets overridden. 

**To reproduce**

1. Go to '[Venia demo page](https://venia.magento.com/)'
2. Scroll down to footer
3. Inspect logo, and particularly:
`<img loading="eager" title="Venia" alt="Venia" class="undefined image-placeholder_layoutOnly-1jH image-placeholder-1mM" height="18" src="img src" width="102">`
4. Placeholder height is incorrect - should be 18px as per element attribute. Instead it's set to auto and gets calculated to 127.5px.

Same issue can be inspected in header logo, but it's harder to visually see, because it overflows.

Expected behavior: `.image-placeholder` should have height of 18px.

**Screenshots**

![image](https://user-images.githubusercontent.com/9033516/158227179-5bdd8436-bab5-4c7e-9222-58d1f47741c2.png)
![image](https://user-images.githubusercontent.com/9033516/158227214-155ae0b3-b69d-4bcb-aa91-01346d8459d2.png)

**Possible solutions**

Instead of adding height as HTML element attribute `height={height}` add it as `style={{height: height + "px"}}'`

**Please complete the following device information:**

-   Device: All
-   Browser: All
-   Browser Version: All
-   Magento Version: Any

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [X] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment] 2022-03-21 14:43
@magento export issue to JIRA project PWA as Bug

**Comment by Sahilsks** [comment] 2023-02-20 04:48
@magento I am working on this

**Comment by glo80771** [comment] 2023-07-12 07:39
Hi @TMNRokas,
The issue is not reproducible as the logo image is taking the height as 18px only.

Please find the steps which I followed for reproducing:
1. Go to '[Venia demo page](https://venia.magento.com/)'
2. Scroll down to footer
3. Inspect logo, and particularly:
      <img loading="eager" title="Venia" alt="Venia" class="undefined image-placeholder_layoutOnly-1jH image-placeholder- 
      1mM" height="18" src="img src" width="102">
4. Placeholder height is incorrect - should be 18px as per element attribute. Instead it's set to auto and gets calculated to 127.5px.

PFA for the screenshot.
<img width="1440" alt="Screenshot 2023-07-12 at 1 00 52 PM" src="https://github.com/magento/pwa-studio/assets/127736464/961bff50-32de-4b62-93e3-f5782a242c25">

**Comment by glo80771** [comment] 2023-08-07 05:24
As there is no update for more than two weeks, we are closing this ticket. Please feel free to open the issue if it still exists.

**Closed by glo80771** 2023-08-07 05:24 UTC
Labels: bug, Progress: ready for grooming, triage-done, Issue: Needs Update
