### ISSUE TITLE
[bug]: Docker can't connect to Magento instance.

### ISSUE THREAD

**Issue by MajorKuprich** [magento/pwa-studio#3154] opened 2021-05-02 17:56 UTC
**Describe the bug**

Docker can't connect to local Magento instance.

**To reproduce**

1. Install Magento 2.4.2 with sample data, base url: https://magento.loc.
2. Install Venia 10.0.0.
3. Set up .env.docker:
```shell
DEV_SERVER_HOST=venia.loc
DEV_SERVER_PORT=5000
DEV_SERVER_SERVICE_WORKER_ENABLED=false
DEV_SERVER_WATCH_OPTIONS_USE_POLLING=0
MAGENTO_BACKEND_URL=https://magento.loc/
CUSTOM_ORIGIN_ENABLED=1
UPWARD_JS_UPWARD_PATH=upward.yml
UPWARD_JS_BIND_LOCAL=1
UPWARD_JS_LOG_URL=1
CHECKOUT_BRAINTREE_TOKEN=sandbox_8yrzsvtm_s2bg8fs563crhqzk
GOOGLE_MAPS_API_KEY=redacted
MAGENTO_BACKEND_EDITION=CE
ENABLE_EXPRESS_SERVER_COMPRESSION=false
```
4. Run the `docker/run-docker` script.
5. Step 9/15 in docker (yarn build) throw errors about not found provided **MAGENTO_BACKEND_URL**.

**Expected behavior**

Yarn inside docker build correctly (access to Magento app).

**Screenshots**

Failed build:

![](https://i.imgur.com/GdQPgYq.png)

**Possible solutions**

Add more explains about start Venia in docker and connection to Magento:
https://github.com/magento/pwa-studio/tree/develop/docker

**Please complete the following device information:**

-   Device: PC
-   Browser: Chrome 90, Firefox 77
-   Magento Version: Magento Open Source 2.4.2

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [x] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment] 2021-05-17 19:17
@magento export issue to JIRA project PWA as Bug

**Comment by glo80771** [comment] 2023-07-19 12:23
Hi @MajorKuprich ,
As per testing, the issue is not reproducible. The following are the steps followed to reproduce:
1. Installed magento
2. Installed Venia
3. Set up the docker file
4. Ran docker/run-docker script.

PFA for the screenshot:
<img width="949" alt="Screenshot 2023-07-19 at 5 49 13 PM" src="https://github.com/magento/pwa-studio/assets/127736464/7861ff32-2061-43ec-aba4-3704e91e6f15">

Please let us know if we are missing anything.

**Comment by glo42707** [comment] 2023-08-04 11:41
closing the ticket since no update from past 2 weeks.
please feel free to reopen if issue still persist.

**Closed by glo42707** 2023-08-04 11:41 UTC
Labels: bug, Progress: ready for grooming, triage-done, Issue: Needs Update
