### ISSUE TITLE
[bug]: Invalid cart validation error

### ISSUE THREAD

**Issue by joseamietta** [magento/pwa-studio#4255] opened 2024-04-26 13:02 UTC
**Describe the bug**

When the cart is invalid, it's never refresh when the language is not en_US

**To reproduce**

1. First of all, you need a backend environment with selected language different of en_US, for example: es_ES
2. Go to the pwa studio page, initilize a cart and wait that backend session expire
3. Then observe the graphQl miniCart response and you will see that error similar to invalid cart in the selected language
5. The cartId never updated unless the localStorage is deleted

**Expected behavior**

That the cart be updated when it's not available and does not depend on the graphQl error

**Screenshots**

![Screenshot from 2024-04-26 09-59-04](https://github.com/magento/pwa-studio/assets/16170859/800a0633-0ab1-48df-a614-09bfb1777176)

**Please complete the following device information:**

-   Device [NoteBook Levono]:
-   Browser [Chrome]:
-   Browser Version [124.0.6367.78 (Official Build) (64-bit)]:
-   Magento Version [Adobe Commerce 2.4.6-p3]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by joseamietta** [comment] 2024-04-26 13:03
@magento I am working on this

**Comment by glo82145** [comment] 2024-05-08 10:23
@adobe export issue to Jira project PWA

**Comment by glo85315** [comment] 2024-08-15 04:40
HI @joseamietta ,
Thank you for bringing this issue to our attention. We’ve thoroughly investigated and attempted to reproduce the problem you described, but unfortunately, we were unable to replicate the issue on our end.
To assist you further, could you please provide any additional details or steps that might help us reproduce the issue

https://github.com/user-attachments/assets/a06d834f-fdd6-44b7-b76d-53718a4472bc

**Comment by joseamietta** [comment] 2024-08-25 23:15
Hi  @glo85315,
You have to leave the cart session or customer session expire, and then reload the page. 
In this moment the active cart isn’t valid and can’t  add a product to cart. Again, it’s necessary that de customer or cart session expire to reproduce it.

**Comment by glo85315** [comment] 2024-08-26 10:41
HI @joseamietta ,
I was unable to reproduce the issue on my end. To better understand and address the problem, could you please provide a video demonstrating the steps to reproduce the issue? This will greatly assist us in resolving it more efficiently.

Thank you for your assistance. I look forward to your response.

https://github.com/user-attachments/assets/c61af82c-f3b0-4cc6-9ab2-4ac15e34d05c

**Comment by glo82145** [comment] 2024-09-23 08:53
As we have got no update from more than 14 days hence we are closing this ticket.
Please feel free to reopen in case of any update.

**Closed by glo82145** 2024-09-23 08:53 UTC
Labels: bug, Progress: ready for grooming, Issue: Needs Update, issue: Cannot Reproduce
