### ISSUE TITLE
Global footer content updates for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#365] opened 2018-10-15 19:32 UTC
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[X] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

https://magento.invisionapp.com/share/WQN5F7BYBPG#/310613558_Home_-_Fully_Loaded

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/09730a2e-7974-461a-ba8a-0bd118f98c48)

Need minor content updates to Venia homepage (footer) based on latest prototype including style and iconography.

- Your Account (link to My Account)
- Follow Us On Instagram (empty link)
- Store Locator (empty link)
- Customer Support

## Expected result:

Updated Venia homepage with minor content changes to footer.

## Possible solutions:

NA

**Comment by zetlen** [comment] 2018-10-19 20:10
Noting that on today's Venia sample data conference call, the SE team said they would explore adding CMS block content.

**Comment by AlexeyKaryka** [comment] 2018-11-09 11:06
@ericerway @awilcoxa Could you please describe how it's possible to get access to the My Account page?

**Comment by Starotitorov** [comment] 2018-11-09 13:15
@zetlen Could you explain your comment https://github.com/magento-research/pwa-studio/issues/365#issuecomment-431484869? Will we receive content for each block as html from CMS? If so, how we will handle links inside each block? I believe it is better to use react-router-dom Link component.

**Comment by zetlen** [comment] 2018-11-09 15:44
@Starotitorov The SE (solution engineering) team owns and maintains the Venia sample content. They created catalog data and media, but they didn't create any CMS example content. That makes it hard for us to test CMS content functionality. We can add CMS content to individual instances, but when those instances are refreshed, we will have to recreate that content. It would be best to add some sample CMS content to the Venia sample data modules. That's what my comment meant.

As for handling links in CMS blocks, we currently inject them as raw HTML, as you can see. That doesn't allow us to replace `<a />` tags with `<Link />` components easily. However, you could capture a DOM ref in `componentDidMount` and then intercept click events bubbling up to that node. You could then change them into `history.push()` calls.

**Comment by AlexeyKaryka** [comment] 2018-11-13 10:59
@zetlen Could you please provide identifier of footer links block if it already exists in venia sample data?

**Comment by AlexeyKaryka** [comment] 2018-11-19 19:38
@zetlen excuse me, could you please repeat how I can share content block for footer links for venia sample data? Am I right that I should propose my changes in the repository of venia sample data, if so could you please share link to this repo, because it seems like there are multiple repos with similar names and I’m not sure what repo I should go to
https://github.com/PMET-public

**Comment by awilcoxa** [comment] 2019-11-21 20:20
Closing this as it's not a bug/defect but an enhancement to current footer design. Will reevaluate as future feature enhancement.

**Closed by awilcoxa** 2019-11-21 20:20 UTC
Labels: bug, pkg:venia-concept
