### ISSUE TITLE
[bug]: wrong file ending for react javascript files

### ISSUE THREAD

**Issue by alexander-kaftan-techdivision** [magento/pwa-studio#2135] opened 2020-02-03 08:24 UTC
The react javascript files should end with .jsx. It may transpiles into correct js but just because of a very nice Transpiler.
Bugs appear if you open the files with an editor/ide:
They may detect plain javascript which causes them to mark the jsx extensions as errors
and provide an incorrect syntax highlighting.

**Comment by awilcoxa** [comment] 2020-02-03 19:52
closing as duplicate of #2127

**Closed by awilcoxa** 2020-02-03 19:52 UTC
Labels: bug
