### ISSUE TITLE
Error in magento-pwa-venia router

### ISSUE THREAD

**Issue by ksandr-dev** [magento/pwa-studio#1322] opened 2019-06-11 03:00 UTC
**venia-concept/src/components/app/renderRoutes.js**
```
<Route exact path="/user/setting" component={userSetting} />
```
**venia-concept/venia-upward.yml**
```
- matches: request.url.pathname
          pattern: '^/user/setting'
          use: userSetting

... ... ...

userSetting:
    inline:
        status: 200
        headers:
            inline:
                content-type: 'text/html'
        body:
            engine: mustache
            template: './templates/userSetting-shell.mst'
            provide:
                bundles: assetManifest.bundles
                isDevelopment: isDevelopment
```

error:
![error_screen](https://user-images.githubusercontent.com/25770330/59240704-7e34f300-8c37-11e9-8def-705face547e3.png)

But in this case, router does works
**venia-concept/src/components/app/renderRoutes.js**
```
<Route exact path="/usersetting" component={userSetting} />
```
**venia-concept/venia-upward.yml**
```
- matches: request.url.pathname
          pattern: '^/usersetting'
          use: userSetting

... ... ...

userSetting:
    inline:
        status: 200
        headers:
            inline:
                content-type: 'text/html'
        body:
            engine: mustache
            template: './templates/userSetting-shell.mst'
            provide:
                bundles: assetManifest.bundles
                isDevelopment: isDevelopment
```

**Comment by threescs** [comment] 2019-06-19 06:36
me too

**Comment by awilcoxa** [comment] 2019-06-24 18:59
team to repro and investigate

**Comment by jaimin-ktpl** [comment] 2019-06-29 12:53
Hello @ksandr-dev , Would you please add the content for file `templates/userSetting-shell.mst`. I have checked the same with `templates/generic-shell.mst` and its working fine with the provided URL structure.

**Comment by sirugh** [comment] 2019-07-10 15:50
@ksandr-dev you need to provide the `userSetting-shell.mst` file otherwise we cannot reproduce. Please do that and I'll re-open this issue.

**Comment by ksandr-dev** [comment] 2019-07-10 15:54
```
{{> templates/open-document}}
    <title>venia</title>
  {{> templates/open-body }}
    <div id="root">
        Loading...
    </div>
  {{> templates/seed-bundles}}
{{> templates/close-document}}
```

**Comment by sirugh** [comment] 2019-07-10 16:03
@ksandr-dev thanks! Can you also provide the component file you use for `userSetting` in `renderRoutes`

**Comment by ksandr-dev** [comment] 2019-07-10 16:09
@sirugh 
sorry, I can't do it. I think it doesn't matter.

```
import react from 'react'

const UserSetting = () => {
  return (<div>user setting</div>);
}

export default UserSetting;
```

**Comment by sirugh** [comment] 2019-07-10 16:26
So I added all this code and I'm still unable to reproduce, sorry. Are you on `develop`? Or 3.0.0? The default bug template has some placeholders for you to provide information that helps us debug.

**Comment by prodev903** [comment] 2019-07-10 18:27
version: 2.1.0

**Comment by ksandr-dev** [comment] 2019-07-10 18:46
same

**Comment by sirugh** [comment] 2019-07-10 19:04
OK -- we're doing some reworking of upward in the latest pwa-studio, so make sure you are developing against `3.0.0` or try develop if you want

**Comment by supernova-at** [comment] 2019-08-13 17:42
Closing this issue as "Cannot Reproduce". Recommended solution is to upgrade to PWA Studio > `3.0.0`.

**Closed by supernova-at** 2019-08-13 17:42 UTC
Labels: bug
