### ISSUE TITLE
[bug]: CHECKOUT_BRAINTREE_TOKEN has changed in PWA Studio Buildpack v5.0.0

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#2308] opened 2020-04-03 23:11 UTC
**Describe the bug**
Buildpack complains about Braintree token, but no clue what the correct value is.

```
⚠  Default value for CHECKOUT_BRAINTREE_TOKEN has changed in PWA Studio Buildpack v5.0.0, due to confusion about whether developers should provide their own Braintree tokens
     for their own sites. An example value is provided instead for development purposes.
     Old value: sandbox_8yrzsvtm_s2bg8fs563crhqzk
     New value: undefined
     This project is using the old default value for CHECKOUT_BRAINTREE_TOKEN. Check to make sure the change does not cause regressions.
```

**To reproduce**
1. Setup a repo as described here: https://magento.github.io/pwa-studio/venia-pwa-concept/setup/

**Expected behavior**
The generated ENV file or DevDocs should provide a working Braintree token out of box, or clearly describe how to bypass this.

**Screenshots**

**Additional context**
Tried:

- Using the sample value
- Commenting out the config line
- Using a fake token

**Possible solutions**
Not sure if we actually have to sign up for Braintree and generate a real (dev) token since 5.x.

In 4.x we just commented this out.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by tjwiebell** [comment] 2020-04-04 21:00
@brendanfalkowski - I see where the confusion lies, and have an idea for improvement.

First, the message output is mostly useless in this case, the only useful piece is at the end `This project is using the old default value for CHECKOUT_BRAINTREE_TOKEN. Check to make sure the change does not cause regressions.`. This was intended to prevent developers from thinking they can use our token with their backend, but has definitely caused a lot of noise during build, which we thought would only affect us internally. If it's going to be common that developers might continue using our development backends, we should fix this.

**Solution**: Suppress the warning if you're using our token **and** our backend. The message is only intended if you're using our token with a custom backend value, so that should be a simple fix.

**Comment by brendanfalkowski** [comment] 2020-04-04 22:51
@tjwiebell – That would work fine for a PR-contribution environment, but what about setting up a client project?

The one I'm working on will not use Braintree, and in fact I've only had one Magento project use Braintree in the last 11 years (in 2013). Nothing against it. It's not my call what payment service a client chooses, so it seems like there should be an obvious escape hatch for "project doesn't need Braintree at all" and the build won't fixate on this.

**Comment by tjwiebell** [comment] 2020-04-05 00:37
@brendanfalkowski - Good points. Since the variable is required you have to provide something, but you will only receive that error if you're using our token. Instead just use `stripe4lyfe` to suppress the warning.

It does appear that `envVarDefinitions` is targetable, so it should be possible to intercept and remove `CHECKOUT_BRAINTREE_TOKEN` from the validation check. Happy to provide you a sample of how to do that if you're interested.

**Comment by tjwiebell** [comment] 2020-04-05 03:00
`intercept.js`
```node
const myName = '@magento/suppress-braintree';
module.exports = targets => {
    const builtins = targets.of('@magento/pwa-buildpack');

    defs.sections.map(section => {
        if (section.name === 'Checkout and payment settings') {
            section.variables = section.variables.filter(
                variableDef =>
                    variableDef.name !== 'CHECKOUT_BRAINTREE_TOKEN'
            );
        }
    });

    builtins.envVarDefinitions.tap(defs => {
        defs.changes = defs.changes.filter(
            changeDef => changeDef.name !== 'CHECKOUT_BRAINTREE_TOKEN'
        );
    });
};
```

Not so bad, but I anticipate as BuildBus becomes more widely used, Braintree would probably be its own package, and payment methods would be a targetable composite, and removing Braintree would be as simple as removing that package dependency.

I'm still going to fix that warning message though, because you've reminded me how annoying it has become 😂

**Comment by brendanfalkowski** [comment] 2020-04-05 05:19
Here's what happens for various Braintree values present in `.env` with:

- Code from 2020-04-04 on `develop` branch.
- `MAGENTO_BACKEND_URL=https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/`
- Run `yarn run build` depending on  while connected to the Cloud site:

Just for my own sanity:

— — — — — — — — — — 

## Case 1: Sandbox value

```
CHECKOUT_BRAINTREE_TOKEN=sandbox_8yrzsvtm_s2bg8fs563crhqzk
```

Gets a WARNING:

```
⚠  Default value for CHECKOUT_BRAINTREE_TOKEN has changed in PWA Studio Buildpack v5.0.0, due
     to confusion about whether developers should provide their own Braintree tokens for their own
     sites. An example value is provided instead for development purposes.
     Old value: sandbox_8yrzsvtm_s2bg8fs563crhqzk
     New value: undefined
     This project is using the old default value for CHECKOUT_BRAINTREE_TOKEN. Check to make sure
     the change does not cause regressions.
```

## Case 2: garbage value

```
CHECKOUT_BRAINTREE_TOKEN=mouse_rat
```

No warning (I had this wrong, I thought I tested and it did still complain).

## Case 3: commented out

```
#CHECKOUT_BRAINTREE_TOKEN=commented_out
```
Gets an ERROR:
```
  ⓧ  Missing required environment variables:
     CHECKOUT_BRAINTREE_TOKEN: Specify a Braintree API token to direct the Venia storefront to communicate with your Braintree
     instance. You can find this value in Braintree's Control Panel under Settings > API Keys > Tokenization Keys. (eg.
     "sandbox_8yrzsvtm_s2bg8fs563crhqzk")
```

**Comment by awilcoxa** [comment] 2020-04-07 16:26
created in Jira backlog fro grooming/prioritization

**Comment by awilcoxa** [comment] 2020-04-13 18:22
Marked as P2S4 during grooming

**Closed** 2020-06-11 18:17 UTC
Labels: Progress: PR created, bug
