### ISSUE TITLE
Magento2 Backend URL

### ISSUE THREAD

**Issue by OneCricketeer** [magento/pwa-studio#4095] opened 2023-04-19 23:02 UTC
**Describe the bug**

Self reporting that `7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud` data-source URL is experiencing downtime. 

Public Github search for all usages - https://github.com/search?q=%227rqtwti-mfwmkrjfqvbjk%22++NOT+is%3Aarchived+NOT+is%3Afork&type=code

**To reproduce**

1. Go to https://develop.pwa-venia.com/ , (or any of the instances in the currently opened PRs)
1. Home page might fail to load initially, or click on any product dropdown (e.g. Tops & Bottoms > Blouses & Skirts)
1. See 404 error page. 
    - Browser DevTools - `{"status":502,"message":"No route known for master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud","additional_error":""}`

**Expected behavior**

The products page load. No 404 pages for main content. No 502 graphql failures. 

**Possible solutions**

Replace the URL. The DNS provider we are using for this `*.magentosite.cloud` instance has informed us that the IDs included with the above address cannot be restored. 😞 

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
  -  The storybook code seems to use this address. 
-   [ ] `venia-ui` 
  - If given the correct URL, the UI will continue to load. But see note above about storybook.
-   [x] `pwa-buildpack`
  -  Anything that configures `MAGENTO_BACKEND_URL` variable. Including the scaffolder's default url parameter. 
-   [ ] `peregrine`
  - If given the correct URL, the UI GraphQL requests will continue to load. 
-   [x] `pwa-devdocs`
  - Check our docs for usages of that address being used as a presentable "example" or "template"
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [x] `create-pwa`
  - See `default_url` param, for example

(Maybe more. These are all I know about)

**Comment by Tarun50745** [comment] 2023-05-04 11:49
Hi @OneCricketeer,

To reproduce the issue we have followed the steps as mentioned in the description above and we are not able to replicate the issue at our end.

**Comment by OneCricketeer** [comment] 2023-05-04 20:50
For `develop-pwa.venia.com`, the instance has changed. In our CI/CD process, I think the mentioned backend url is still used, as well as in the `create-pwa` script

**Comment by Tarun50745** [comment] 2023-05-05 05:53
Hi @OneCricketeer,

As mentioned previously, this URL  develop-pwa.venia.com is working as expected.

Can we close this issue ?

Below is the screenshot -
![Uploading Screenshot 2023-05-05 at 11.22.38 AM.png…]()

**Comment by glo42707** [comment] 2023-05-23 13:06
hey @OneCricketeer 

thanks for raising request.

we will update latest working CI environment as https://master-7rqtwti-c5v7sxvquxwl4.eu-4.magentosite.cloud/ 

since the older env is not working due to deletion 7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud

**Comment by glo42707** [comment] 2023-05-23 13:08
@adobe export issue to JIRA project PWA as Bug

**Closed** 2023-05-25 12:39 UTC
Labels: bug, Effort: 3-Large, Priority: P1, Progress: done, Issue: Confirm

**Comment by glo82145** [comment] 2023-06-01 07:52
Hello,
As I can see this issue got fixed in the scope of the internal Jira ticket [PWA-3155](https://jira.corp.adobe.com/browse/PWA-3155) 
Related commits:[https://github.com/magento-commerce/pwa-studio-cicd/commit/1da6822926fef1c0759a69e6d9ced35e6bb24e25]
[https://github.com/magento/pwa-studio/commit/836aa40608465ccc28066d4fbdddee3a6a560b75]

Thanks
