### ISSUE TITLE
[bug]: PageBuider crashes on IE11

### ISSUE THREAD

**Issue by denisn-ewave** [magento/pwa-studio#2469] opened 2020-06-09 08:31 UTC
**Describe the bug**
Empty page is displayed if use PageBuider package on IE11

**To reproduce**
1. Open any page where used 'PageBuider'
2. Open console
3. See syntax error

**Expected behavior**
Page Builder does not break page on IE11

**Screenshots**
![ie11-console](https://user-images.githubusercontent.com/66664396/84124928-87bc8b00-aa44-11ea-8bb3-f785e9ba6ec3.jpg)

![ie11-error-file](https://user-images.githubusercontent.com/66664396/84125028-a6bb1d00-aa44-11ea-907e-63ff343f60be.jpg)

**Possible solutions**
Similar issue - https://github.com/webcomponents/webcomponentsjs/pull/560

**Please complete the following device information:**
 - OS: Windows 10
 - Browser : IE
 - Browser Version: 11
 - "@magento/pagebuilder": "1.0.1"
 - NPM version `npm -v`: 6.13.4
 - Node Version `node -v`: 12.16.1

**Comment by tjwiebell** [comment] 2020-06-09 13:22
The PageBuilder extension for PWA Studio does not support IE11, you can find our supported browsers requirement here:

https://github.com/magento/pwa-studio/wiki/Definition-of-Quality#browser-support

Closing as not a bug.

**Closed by tjwiebell** 2020-06-09 13:22 UTC
Labels: bug
