### ISSUE TITLE
 .env.dist is not present here

### ISSUE THREAD

**Issue by sumeet-synergytop** [magento/pwa-studio#2242] opened 2020-03-12 08:49 UTC
.env.dist is not present here when get clone then  .env.dist is not in packages/venia-concept

**Comment by tjwiebell** [comment] 2020-04-07 16:03
`.env` creation is a CLI command in buildpack, we do not distribute a `.env.dist`.

https://magento.github.io/pwa-studio/venia-pwa-concept/setup/#step-4-create-the-env-file

Closing as not a bug, but please let us know if there is outdated documentation somewhere that set this expectation.

**Closed by tjwiebell** 2020-04-07 16:03 UTC
Labels: bug
