### ISSUE TITLE
[bug]: URLs are not set for breadcrumbs they are all linking to the current page

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#2231] opened 2020-03-10 09:58 UTC
**Describe the bug**
The breadcrumbs don't seem to link to the proper url

**To reproduce**
1. Go to https://venia.magento.com/shop-the-look/minimalist-sensibility.html
2. Check link behind 'Shop the Look'
3. Confirm this is the same url you are already on

**Expected behavior**
Every breadcrumb should have it's own link

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment] 2020-03-10 13:26
Doesn't look like this is a bug in develop: https://develop.pwa-venia.com/shop-the-look/minimalist-sensibility.html

Originally the intermediate breadcrumbs did this because there was no data for how to get to that category. So it was intentional. Probably should have just left them without underline or something.

Anyways, closing as not a bug!

**Closed by sirugh** 2020-03-10 13:26 UTC
Labels: bug, help wanted
