### ISSUE TITLE
[bug]: Order history crash on Items Gives JS Error

### ISSUE THREAD

**Issue by mruduramaig** [magento/pwa-studio#4154] opened 2023-08-10 06:57 UTC
**Steps to reproduce the behavior:**

1. Login to Venia
2. Place an order with the product that has an image or No Image
3. View order history

**Expected behavior**
Can view the order normally

**Actual**
Application crashes with error

**Screenshots**
![MicrosoftTeams-image (8)](https://github.com/magento/pwa-studio/assets/46807556/51982ea4-2325-4889-820d-3a4e7a49f1f1)

**Comment by glo42707** [comment] 2023-08-17 15:34
hi @mruduramaig 

as per testing we are not able to reproduce issue and able to open order history without any error as per following your steps  of description.

**Attachment**
![image](https://github.com/magento/pwa-studio/assets/84493875/d867ebd4-9ddf-4024-89b6-f0dc8693ecd0)


Please let us know if we are missing anyting

**Comment by mruduramaig** [comment] 2023-08-21 05:47
@glo42707 We rebuilt the PWA instance. The JS issue has been resolved.
Now we have a new issue When a new order is placed subtotal and Tax are displayed as $ 0.

**Comment by glo42707** [comment] 2023-08-21 05:57
hey @mruduramaig 

Thanks for replying, since issue resolve we are closing this ticket which was related to JS error and which is not reproducible at our end.

also for TAX and subtotal I would suggest you to please check your magento backend configuration in case any configuration was chaged by you or your team since at our end it is working as expected.

still if you face tax issue / anyother issue, kindly raise a new ticket since that would be different error all togather.

Regards

**Closed by glo42707** 2023-08-21 05:57 UTC
Labels: bug, triage-done, Issue: Needs Update, issue: Cannot Reproduce
