### ISSUE TITLE
[feature]: Skip isTTY check on run when using secure host if automating

### ISSUE THREAD

**Issue by furan917** [magento/pwa-studio#1194] opened 2019-05-02 16:54 UTC
**Is your feature request related to a problem? Please describe.**  
When using any kind of automation scripting it gets killed at `/pwa-buildpack/dist/Utilities/configureHost.js:Ln 60` as it absolutely has to find a interactable terminal. 

**Describe the solution you'd like**  
I would like this if statement to be updated to have an or `||` statement, something like 
`(process.stdin.isTTY || process.env.AVOID_ISTTY_CHECK)` so that automation scripting which bypasses the need for the prompt check can avoid this hard check and carry on. This way it can either be done via setting it hard coded into the environment, in a docker `environment:` argument or even simply within the .env file provided by `venia-concept` package as `AVOID_ISTTY_CHECK=1` with a default to define it as 0.

**Describe alternatives you've considered**  
I have not came up with any alternatives short of my automation software using
a hack like `sed -e "s/process.stdin.isTTY/!process.stdin.isTTY/g" -i packages/pwa-buildpack/dist/Utilities/configureHost.js` after the `yarn build`

**Additional context**  
Any other alternatives would be greatly appreciated as well but it was an issue I came up against today and forced me to try a very hacky workaround to bypass it. 

**Please let us know what packages this feature is in regards to:**  
- [x] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by tjwiebell** [comment] 2019-05-02 18:01
@furan917 

Can you clarify the steps you're taking to reproduce this behavior? I'm assuming you're trying to run `yarn watch:venia` inside of a Docker container, or something that doesn't have an interactive shell? You may want to look at the developer docker .env `docker/.env.docker.dev`, which uses parameters that allows it to roll its own host config and certificates to get around this problem (specifically `MAGENTO_BUILDPACK_PROVIDE_SECURE_HOST=0`).

We also have a lot of CICD changes in flight that may also address this issue, but again, I think we rely on skipping this step in buildpack, and configure our own host. I'll check with the devs who worked on that, and see if they can provide some additional advice.

**Comment by furan917** [comment] 2019-05-02 18:46
@tjwiebell Hey, yeah you are right its a dockerized container, though I was also looking into a scripted virtual machine (via vagrant or valet+) for one of our devs on windows in case of any weird dockerish issues crop up. 

I had looked at the current docker setup and it uses jwilder/nginx-proxy and imports its SSLs which we don't, we have our own nginx with customised route mapping for all our localhost sites and using the proxy pass worked with only issues on the validity of the host header we were passing with it (fixed by setting host to 0.0.0.0) - but also didn't give us quick and easy https. Using the `MAGENTO_BUILDPACK_PROVIDE_SECURE_HOST=1` with a custom host allows us to just easily get that setup with the small issue I had above.

But you are right, it is when running `yarn watch:venia` or  `yarn workspace @magento/venia-concept run watch -- --host docker.pwa.local`

**Comment by awilcoxa** [comment] 2019-08-05 18:47
possibly addressed in #1498

**Comment by zetlen** [comment] 2019-08-07 13:45
I believe this has been fixed for a while, since `interactive` was an option in `configureHost`. If you're using Docker and you have an SSL terminator that works differently, then probably your best bet is to avoid `configureHost` altogether, which you can do by setting `CUSTOM_ORIGIN_ENABLED=0`.

**Comment by awilcoxa** [comment] 2020-02-03 18:01
closing as resolved, if additional issues exist specific to this issue please re-open

**Closed by awilcoxa** 2020-02-03 18:01 UTC
Labels: enhancement
