### ISSUE TITLE
[bug]: When venia is hosted on docker, network requests run queued

### ISSUE THREAD

**Issue by skisielewicz9bits** [magento/pwa-studio#3770] opened 2022-04-19 13:48 UTC
**Describe the bug**

We are facing performance issues in our project based on venia concept, main issue for now are as in the topic queued requests ran from storefront. When we launch the upward server on main OS(Ubuntu 21.10) everything seems fine as in the screenshoot below:
![image](https://user-images.githubusercontent.com/104010814/164017453-d434f26e-a1ef-4369-9cff-faec7162b485.png)
The problem starts when app is dockerized:
![image](https://user-images.githubusercontent.com/104010814/164017607-110ac330-c7c6-46b4-b439-5049e18d6686.png)
Venia demo is facing same issue as I described:
![image](https://user-images.githubusercontent.com/104010814/164017755-3ad64734-ebcd-4dec-b9ce-24449b26094e.png)

**To reproduce**

Run any implementation based on pwa studio dockerized, check devtools network requests waterfall for xhr/fetch requests.

**Expected behavior**

Parallel on dockerized app as it works without docker. 

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [x] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment] 2022-04-25 14:11
@magento export issue to JIRA project PWA as Bug

**Comment by OneCricketeer** [comment] 2022-04-27 16:32
@skisielewicz9bits Would you mind sharing your docker-run command(s)?

**Comment by skisielewicz9bits** [comment] 2022-04-28 07:31
@OneCricketeer hey, we are facing this issue on every setup(staging or local), here is my dockerfile for local development:
`##############################################################
# This file is intended to be used with ./docker-compose.yml #
##############################################################

FROM node:16.6.0-alpine as build
# working directory
WORKDIR /usr/src/app

# global environment setup : yarn + dependencies needed to support node-gyp
RUN apk --no-cache --virtual add \
    python3 \
    make \
    g++ \
    yarn

# copy root dependency files and configs needed for install
COPY package.json yarn.lock ./

# run yarn install to get fresh packages
RUN yarn install --frozen-lockfile

COPY src ./src
COPY templates ./templates
COPY CENSORED-static ./CENSORED-static
COPY i18n ./i18n
COPY local-intercept.js babel.config.js server.js template.html template-dev.html upward.yml webpack.config.js .graphqlconfig magento-compatibility.js ./

# pass necessary env vars to build process
ARG MAGENTO_BACKEND_URL
ARG CHECKOUT_BRAINTREE_TOKEN
ARG ENTRY_TEMPLATE_PATH
ARG GTM_CODE

# command to run application
CMD [ "yarn", "run", "watch"]`

**Comment by skisielewicz9bits** [comment] 2022-05-02 06:32
No, commad that is launching container is based on that https://github.com/magento/pwa-studio/blob/develop/docker/run-docker

**Comment by OneCricketeer** [comment] 2022-05-02 13:27
Thanks

I see that's using the included docker-compose. Just wanted to verify you're not modifying anything with that

**Comment by skisielewicz9bits** [comment] 2022-05-02 13:55
@OneCricketeer no, we just added few env vars

**Comment by tuyennn** [comment] 2022-11-24 06:56
@skisielewicz9bits any update or your workaround on this?

**Comment by glo82145** [comment] 2023-07-12 06:09
@skisielewicz9bits We are not able to reproduce this issue by following the steps given above. Please help us know if any step is missing.

**Comment by glo82145** [comment] 2023-07-26 06:06
As we have not received any update on the same, hence we are closing it.

**Closed by glo82145** 2023-07-26 06:06 UTC
Labels: bug, Progress: ready for dev, Issue: Needs Update
