### ISSUE TITLE
[bug]: Yarn test doesn't run, because it's missing in package.json

### ISSUE THREAD

**Issue by caedes** [magento/pwa-studio#2965] opened 2021-01-22 08:56 UTC
**Describe the bug**
Wanting to run my test suite, but failed because no `test` script was found in `package.json`.

**To reproduce**
1. Create a new project with `yarn create @magento/pwa`.
2. Default answer everywhere.
3. `yarn test` failed.

**Expected behavior**
A test script, with Jest, as I see it somewhere in the doc.

**Screenshots**
<img width="614" alt="Capture d’écran 2021-01-22 à 09 42 39" src="https://user-images.githubusercontent.com/1019321/105468252-1362ef00-5c97-11eb-9737-92f2ee526bfc.png">

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device: MacBook Pro
 - OS: Catalina v10.15.7
 - PWA Studio Version: 1.1.2
 - NPM version `npm -v`: 6.14.11
 - Node Version `node -v`: 14.15.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

**Comment by sirugh** [comment] 2021-01-22 15:40
Hi there @caedes, and thanks for shining a light on this! Unfortunately, this is not a "bug" but is actually an intentional choice we made to [remove the out-of-the-box tests](https://github.com/magento/pwa-studio/pull/2321) from the scaffold. 

For now, the addition of a test runner to your scaffolded app entirely your choice! You can pick your own test runner, and implement tests for your custom components however you would like. That said, I can see the desire to have a basic example in place so it's one less thing to worry about when scaffolding a PWA Studio app. I have created an internal ticket to track that feature request: https://jira.corp.magento.com/browse/PWA-1340

I'm going to close this issue as it's not a bug. I would recommend hopping on the public slack channel to ask for help with this.

**Closed by sirugh** 2021-01-22 15:40 UTC
Labels: Progress: ready for grooming, bug
