### ISSUE TITLE
[bug]: token is not being sent to the request headers, meaning that data is not rendered after login.

### ISSUE THREAD

**Issue by Cyber-Root0** [magento/pwa-studio#4263] opened 2024-05-07 12:57 UTC
**token is not being sent to the request headers, meaning that data is not rendered after login.**

**To reproduce**

I just carried out a compilation without modifying the main repository, and linked it to Magento perfectly, without errors so far, just the issue of client authentication. Cart and checkout are normal

**Rendering customer information after login.**

**Screenshots**

![magento-authcustomerpwa](https://github.com/magento/pwa-studio/assets/70926805/0b95153e-ccb8-4d26-b99c-919ea943b699)
![loop-onrender](https://github.com/magento/pwa-studio/assets/70926805/887571b4-cb1d-4af9-a76b-8abc344fb6f4)

**Possible solutions**

I thought for a moment that it was some Magento configuration, but when sending the token manually via Graphql the data was displayed perfectly.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [All Devices]:
-   Browser [All Browsers]:
-   Browser Version [Last version: 13.3.0]:
-   Magento Version [e.g Magento 2.4.6 Open Source]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [X] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by glo82145** [comment] 2024-05-08 10:21
@adobe export issue to Jira project PWA

**Comment by glo85315** [comment] 2024-05-08 10:46
[@adobe](https://github.com/adobe) export issue to Jira project PWA

**Comment by glo85315** [comment] 2024-05-13 02:35
Hi @Cyber-Root0 , am not able to reproduce the issue. please add steps to reproduce the issue and **please also add video of this issue**. this is help us to reproduce the issue

**Comment by glo82145** [comment] 2024-05-29 10:45
As We have waited for more than 14 days for any update on this issue, hence we are closing this issue.

Feel free to reopen it any case of any update.

**Closed by glo82145** 2024-05-29 10:45 UTC
Labels: bug, Progress: ready for grooming
