### ISSUE TITLE
[bug]: Row element with parallax fails to rerender with correct background image

### ISSUE THREAD

**Issue by syno-aee** [magento/pwa-studio#3986] opened 2022-10-19 13:28 UTC
**Describe the bug**

When navigating between two CMS pages each containing a row element, if the second page's row has parallax on its background the component fails to re-render with the correct background image and instead keeps the background image from the previous page.

**To reproduce**

1. On a freshly installed Venia app, add a row as first element of your homepage with a background image.
2. Create a new CMS page also containing a row as first element, with a different background image, and **parallax enabled**.
3. In each of these rows create a button targeting the other page to help illustrate the problem.
4. On your frontend, go to your homepage and use the buttons in your first row to navigate to your custom CMS page. When navigating for the first time, the rendered background image will be the correct one.
5. Navigate back to your homepage and then back to your custom CMS page again. The background image is now wrong.

**Expected behavior**

The row's rendered background image should be the correct one, as configured in the back-office.

**Screenshots**

![Peek 2022-10-19 15-19](https://user-images.githubusercontent.com/49021066/196702619-4c612bc5-c179-4cd8-b387-d0ba1be81877.gif)

**Possible solutions**

I don't have a solution in mind but the problem seems to originate from the useEffect hook handling the update of the background image when parallax is active, on line 155 in @magento/pagebuilder/lib/ContentTypes/Row/row.js

**Please complete the following device information:**

-   Chrome 106
-   Magento 2.4.5
-   PWA Studio 12.6

**Please let us know what packages this bug is in regards to:**

-   @magento/pagebuilder

**Comment by anthoula** [comment] 2022-10-25 14:20
@adobe export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment] 2022-10-25 17:09
Thanks for reporting this. We can accept a contribution if community would like to submit a pull request.

**Comment by glo80771** [comment] 2023-05-31 13:01
Hey @syno-aee , 
As per testing the issue on PWA-13.1.0, we are not able to reproduce it from the following steps.

1. On a freshly installed Venia app, add a row as first element of your homepage with a background image.
2. Create a new CMS page also containing a row as first element, with a different background image, and parallax enabled.
3. In each of these rows create a button targeting the other page to help illustrate the problem.
4. On your frontend, go to your homepage and use the buttons in your first row to navigate to your custom CMS page. When navigating for the first time, the rendered background image will be the correct one.
5. Navigate back to your homepage and then back to your custom CMS page again. The background image is now wrong.

Kindly let us know if we are missing anything to reproduce the issue.

Attached video:
https://github.com/magento/pwa-studio/assets/127736464/2d61a094-04d0-476f-8421-8f39daa58906

**Comment by glo82145** [comment] 2023-06-19 06:08
We waited for more than 14 days for update on this issue, hence we are closing it. 
Please feel free to reopen if you are still have any update on the same.

**Closed by glo82145** 2023-06-19 06:08 UTC
Labels: bug, help wanted, Progress: PR review, Issue: Needs Update
