### ISSUE TITLE
[bug]: Not getting customer id in the brain tree transaction object response.

### ISSUE THREAD

**Issue by prajeswari** [magento/pwa-studio#4155] opened 2023-08-10 10:24 UTC
**Describe the bug**
I am not getting customer id in the brain tree transaction response while using Magento 2.4.6 and 2.4.6 P1 EE with PWA venia-ui store. I have verified same in Magento 2.4.5 EE and 2.4.4 EE version I am getting customer id in the response.
**To reproduce**

-Install PWA venia store and point it to any of Magento 2.4.6 EE instance.
-configure braintree 
-And place an order with Brain Tree and verify the transaction response. 
**Expected behavior**

Customer id should be there in the response 
**Screenshots**

Response In 2.4.6
![Selection_722](https://github.com/magento/pwa-studio/assets/78781200/7c20b54d-ea81-4a4f-b13f-9a64d701ca55)

**Please complete the following device information:**

-   Magento Version : 2.4.6 EE and 2.4.6 P1 EE
- 
**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`
- 
Magento git repo poseted link
https://github.com/magento/magento2/issues/37887

**Comment by glo80771** [comment] 2023-12-13 06:19
Hi @prajeswari ,
The issue is reproducible with Magento setup as well as in Pwa. Please find the JIRA ticket which was already created for the issue(https://jira.corp.adobe.com/browse/AC-9369). Hence confirming the issue.

**Comment by prajeswari** [comment] 2024-01-23 04:47
Hi @glo80771 ,

Any update on this issue? I have a dependency on it.

**Comment by glo82145** [comment] 2024-05-09 09:08
[@adobe](https://github.com/adobe) export issue to Jira project PWA

**Comment by glo82145** [comment] 2024-05-09 09:12
@adobe export issue to Jira project PWA

**Comment by glo42707** [comment] 2024-10-29 03:11
closing this ticket since as per discussion with core braintree Dev Team, it is expected Behaviour which implemented from 2.4.6 magento release also when user enable vault feature from backend it will start working.

please feel free to reopen in case any more queries or still reproducible.

**Closed** 2024-10-29 03:10 UTC
Labels: bug, Progress: done, triage-done
