### ISSUE TITLE
[bug]: error [pertain] "@magento/venia-ui" declares a "pwa-studio.targets.declare"

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2301] opened 2020-04-01 01:32 UTC
**Describe the bug**
Can't start dev server with PWA Studio 6.0.0-beta1

**To reproduce**

1. git clone git@github.com:magento/pwa-studio.git tmp-pwa-create
2. cd tmp-pwa-create
3. git checkout release/6.0
4. yarn install
5. DEBUG_PROJECT_CREATION=1 packages/create-pwa/bin/create-pwa
6. cd into new project folder, ie my-project
6. yarn watch

```
yarn run v1.22.0
$ webpack-dev-server --progress --color --env.mode development
Error: [pertain] "@magento/venia-ui" declares a "pwa-studio.targets.declare" module, but Node could not find a valid JS module to load from "/Users/kristof/Projects/tmp-pwa-create/my-project/node_modules/@magento/venia-ui/targets/declare"
    at ExplicitDependency.pertains (/Users/kristof/Projects/tmp-pwa-create/my-project/node_modules/pertain/build/main/ExplicitDependency.js:71:19)
    at pertaining.dependencies.filter.dependency (/Users/kristof/Projects/tmp-pwa-create/my-project/node_modules/pertain/build/main/ExplicitDependencySet.js:27:82)
    at Array.filter (<anonymous>)
    at ExplicitDependencySet.pertaining (/Users/kristof/Projects/tmp-pwa-create/my-project/node_modules/pertain/build/main/ExplicitDependencySet.js:27:50)
    at pertain (/Users/kristof/Projects/tmp-pwa-create/my-project/node_modules/pertain/build/main/pertain.js:44:19)
    at BuildBus.runPhase (/Users/kristof/Projects/tmp-pwa-create/my-project/node_modules/@magento/pwa-buildpack/lib/BuildBus/BuildBus.js:68:9)
    at Function.for (/Users/kristof/Projects/tmp-pwa-create/my-project/node_modules/@magento/pwa-buildpack/lib/BuildBus/BuildBus.js:25:13)
    at configureWebpack (/Users/kristof/Projects/tmp-pwa-create/my-project/node_modules/@magento/pwa-buildpack/lib/WebpackTools/configureWebpack.js:71:29)
✨  Done in 6.83s.
```

**Expected behavior**
No error message.

**Possible solutions**
There is no targets folder in node_modules/@magento/venia-ui/

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version: 2.3.3
 - PWA Studio Version: 6.0.0-beta1
 - NPM version `npm -v`: 6.13.4
 - Node Version `node -v`: v10.18.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

**Comment by zetlen** [comment] 2020-04-01 17:47
Thanks @fooman and sorry about this silly bug. The diagnosis from @tjwiebell is accurate and this should be fixed in https://github.com/magento/pwa-studio/pull/2305/files.

This happened because we use the `files` property of `package.json` to restrict which files are published to NPM. This is a good practice, because it makes the packages lighter and quicker to install, but the pattern didn't include the new directory.

**Closed** 2020-04-01 20:46 UTC
Labels: Progress: PR created, bug

**Comment by fooman** [comment] 2020-04-01 21:12
No worries - that's why we have pre-releases right?

Happy to report that I can confirm beta2 solves this.

**Comment by ksaleem25** [comment] 2020-04-20 22:50
@tjwiebell  the issue seems to be back in rc1
![image](https://user-images.githubusercontent.com/17887732/79806989-26046c80-8383-11ea-92d1-16e7bc62ffc3.png)

**Comment by tjwiebell** [comment] 2020-04-20 23:04
@ksaleem25 - I was unable to reproduce this locally (Node 10, `npm` and `yarn` both worked). Please open a new bug with all your environment details and we can investigate further.
