### ISSUE TITLE
Payment Problem

### ISSUE THREAD

**Issue by jaballah-dorsaf** [magento/pwa-studio#3511] opened 2021-10-25 09:39 UTC
Hello ! I installed pwa-concept v12 and I am using Magento 2.4.3-p1 back-end, I found a problem When ordering a product at the stage of filling out the payment form despite the desktop version it works fine, you find a screenshot which explains the problem in the console, thanks for your he
![Capture2](https://user-images.githubusercontent.com/55697769/138672613-726fe91f-3ba4-4f1f-830e-68033c4e9074.PNG)
l
![Capture](https://user-images.githubusercontent.com/55697769/138672623-08c2f476-5a9d-4236-92d9-65165a1c1620.PNG)
p

**Comment by supernova-at** [comment] 2021-11-16 21:33
Closing as duplicate of #3510 (thanks @Watch3ruk )

**Closed by supernova-at** 2021-11-16 21:33 UTC
Labels: bug
