### ISSUE TITLE
[feature]: When a user hovers over or presses into a toast the timeout should pause

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#1284] opened 2019-05-31 15:14 UTC
**Is your feature request related to a problem? Please describe.**
When a user hovers on a toast or clicks in a toast (not the dismiss/cta) or presses on it as in a mobile press to copy the text we should **pause** the timeout. Imagine a short-living toast that has some text a user wants to copy so they click into it to copy but it disappears. That would be frustrating!

**Describe the solution you'd like**
[react-toast-notifications](https://github.com/jossmac/react-toast-notifications) has an interesting take, basically they wrap their toasts with a controller that manages the state. We can do something like that but it's probably something that should live in the presentation layer which may add complexity. **Specifically** the removal timeout is created/removed within the action/reducer but pausing a timeout would live in the display, which means we probably are going to need to refactor how timeouts are managed.

**Describe alternatives you've considered**
Current alternative is that a toast with information that a user may want to copy (like an error) should have a long `timeout` value for now.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by supernova-at** [comment] 2019-06-18 13:28
Desired UX likely includes pausing **all** toast timeouts on hover of any individual toast.

If a user is attempting to copy the text of the third toast in a list of seven, and other toasts below it start disappearing because their timeout expires, that would be frustrating as well.

**Comment by jflanaganuk** [comment] 2019-06-18 15:31
#mmuk2019

**Comment by awilcoxa** [comment] 2019-07-22 18:53
Moving to backlog, toasts feature is working as designed. This enhancement adds value but currently not a high priority. Will re-evaluate for future release.

**Closed** 2021-05-17 20:16 UTC
Labels: enhancement, needs-ux, pkg:peregrine, pkg:venia-concept
