### ISSUE TITLE
[feature]: Checkout success page

### ISSUE THREAD

**Issue by rafaelstz** [magento/pwa-studio#4074] opened 2023-03-29 20:45 UTC
**Is your feature request related to a problem? Please describe.**
There are many tools that will create a funnel of customer journeys based on URLs, it doesn't work on PWA Studio because we just have /cart and /checkout, but a /checkout/success page is missing.

**Describe the solution you'd like**
Create a checkout success route.

**Describe alternatives you've considered**
Push data with JS events.

**Additional context**
The alternative solution works with Google Analytics, but not with New Relic and other tools. Even Google Analytics makes the process harder to implement.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [x] `upward-js`
- [x] `upward-spec`
- [ ] `create-pwa`

**Comment by tkacheva** [comment] 2023-07-14 22:14
@rafaelstz have you tried to subscribe to the [event](https://developer.adobe.com/commerce/pwa-studio/api/events/#order_confirmation_page_view) PWA Studio register?

**Comment by rafaelstz** [comment] 2023-08-11 22:41
Yes, it solved the issue but it made the process longer since we have to do it for Klaviyo, GTM, New Relic... Those third-party scripts rely on the URLs in a generic reliable way, it works on Adobe Commerce Monolithic, and I believe it would make integration easier by having the same pattern on PWA Studio.

**Comment by glo42707** [comment] 2023-08-17 09:29
closing the ticket since issue resolved as per reporter and on PWA sturdio for event capture users need to subscribe 'event' feature as per above comment..

please feel free to reopen ticket in case still reproducble.

**Closed by glo42707** 2023-08-17 09:29 UTC
Labels: enhancement, triage-done
