### ISSUE TITLE
Wrong version in .env while creating createDotEnvFile

### ISSUE THREAD

**Issue by arjunadobe** [magento/pwa-studio#2606] opened 2020-08-04 17:09 UTC
[**Describe](url) the bug**
I have created a project using "yarn create @magento/pwa". 

 When the package was installed we are creating a .env file and the file responsible to create the ".env file " is this "pwa-buildpack\lib\Utilities\createDotEnvFile.js". 
 
 When I looked in to the ".env "file, It has Invalid Version Description  "Generated by @magento/pwa-buildpack v5.1.1 on 2020-08-04T10:50:31.172Z.". 
 

**To reproduce**
yarn create @magento/pwa
Complete the setup
Now open the ".env" file

**Expected behavior**
 The right version should be "6.0.0" instead of "v51.1".

**Screenshots**

`Generated by @magento/pwa-buildpack v5.1.1 on 2020-08-04T10:50:31.172Z.`
![image](https://user-images.githubusercontent.com/51747982/89323586-8d7cc880-d6a3-11ea-9bb2-f0290bb3cf7b.png)

**Please complete the following device information:**
 - Magento Version: 2.3.3
 - PWA Studio Version: v7.0
 - NPM version `npm -v`: 6.14.7
 - Node Version `node -v`: v14.7.0
 - Yarn Version: 1.22.4

**Please let us know what packages this bug is in regards to:**
**- [ ]   `pwa-buildpack`**

**Comment by jemoon** [comment] 2020-08-06 19:14
@arjunadobe I think that the issue is just because latest version of create-pwa package was not published on npm yet and once it will be published version of pwa-buildpack will be 6.0.0.

In order to scaffold latest version now You can also use alternative method which is described here https://magento.github.io/pwa-studio/pwa-buildpack/reference/buildpack-cli/create-project/ as pwa-buildback in latest version was already published on npm. Here is the result:
![image](https://user-images.githubusercontent.com/3430741/89572670-bb8c1500-d829-11ea-9b6a-56a17a4e60ff.png)

**Comment by arjunadobe** [comment] 2020-08-07 10:29
Ok Thanks @jemoon

**Comment by tjwiebell** [comment] 2020-10-20 15:40
This has been resolved in the latest release, closing as no longer a bug.

**Closed by tjwiebell** 2020-10-20 15:40 UTC
Labels: bug
