### ISSUE TITLE
Stuck during package installation.

### ISSUE THREAD

**Issue by cnspary** [magento/pwa-studio#4259] opened 2024-05-06 06:45 UTC
**Install Env:**
```
node version: v21.4.0
npm version: v10.2.4
@magento/venia-concept version:  12.1.0
```

**Problem:**

when I install @magento/venia-concept@12.1.0 by command `npm install @magento/venia-concept@12.1.0`, the **installation process gets stuck and never ends**. CPU usage will rise to 100%. Memory usage will also rise and will never be freed.

Can someone helps check this out?

**Comment by cnspary** [comment] 2024-05-06 06:46
@magento I am working on this

**Comment by glo42707** [comment] 2024-06-06 11:14
@cnspary 
could you please provide all the steps you followed for pwa installation so we would provide you clear information.
also if you can help us to know which document are you reffering for pwa setup.

**Comment by glo42707** [comment] 2024-06-17 05:33
closing this ticket since no reply from reporter for last 2 weeks and tested this ticket for installation which is workin fine at QA's systems
please feel free to reopen with clear steps in case still reproducible.

**Closed** 2024-06-17 05:32 UTC
Labels: Progress: done
