### ISSUE TITLE
[bug]: Can't click on First level categroy in Navigation

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/pwa-studio#2274] opened 2020-03-23 07:16 UTC
**Describe the bug**
We can't go on first level category when clicking on left navigation but we can go when we will click on home page categories

**To reproduce**
1. Open develop site https://develop.pwa-venia.com/
2. Click on home page categories (It's working fine)
3. Click on left side navigation first-level categories (This is not working)

**Expected behavior**
Left side navigation first leval categories should redirect to category

**Screenshots**
![Home Page   Venia](https://user-images.githubusercontent.com/23443991/77291318-01759000-6d04-11ea-9f4c-7723c4b69ced.png)

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment] 2020-03-23 17:22
I just tried it and the left nav appears to be functioning as intended:

[![Image from Gyazo](https://i.gyazo.com/c9face54395bb6d9783098ab6da53335.gif)](https://gyazo.com/c9face54395bb6d9783098ab6da53335)

If you meant that you should be able to click "Bottoms" and go to the "Bottoms" category page from left nav, that is not how we originally wrote the feature. I'm going to close this as not a bug but if you feel that the left nav could be improved please open a feature request and we will get to it when we can. Thanks!

**Closed by sirugh** 2020-03-23 17:22 UTC
Labels: bug

**Comment by hitesh-wagento** [comment] 2020-03-24 03:34
Hi @sirugh 

If I am customer and I want to buy bottom how can I go that category? because I can go when click on home page category

**Comment by sirugh** [comment] 2020-03-24 03:40
I would use the home page button for "Bottoms" in that case. However you may be onto something - there might not be an easy way to access intermediate categories. For example, were Bottoms -> Shorts -> Men's Shorts the categories available how would you get to Shorts? Still, glad you opened a new feature request. :)

**Comment by hitesh-wagento** [comment] 2020-03-24 03:49
Hi @sirugh 

For example, when I will click on Bottom it' redirect luma or open *All Bottom* Like Magento2
![Home Page](https://user-images.githubusercontent.com/23443991/77386324-91711380-6db0-11ea-813d-2592a74b2c17.png)


I have created feature request #2276
