### ISSUE TITLE
[doc]: Debugging and Troubleshooting Guides

### ISSUE THREAD

**Issue by awilcoxa** [magento/pwa-studio#1805] opened 2019-09-27 18:34 UTC
Create or improve existing documentation to clearly define steps/guides for troubleshooting and debugging when running into issues with PWA Studio. Additional discovery required to identify topics/common problem areas. 

**Please let us know whether this is a new topic or a topic change request:**
 - [ x] New Topic Request (ie. missing entire topic/section)
 - [ x] Topic Change Request (ie. spelling, organization)

**Comment by jcalcaben** [comment] 2019-09-30 14:28
@jeff-matthews is this something that the knowledge-base team needs to be responsible for or the docs team?

**Comment by jeff-matthews** [comment] 2019-09-30 14:41
I'm glad you asked @jcalcaben! Troubleshooting content belongs on the [Magento Knowledge Base](https://support.magento.com/hc/en-us), so it's the Support team's responsibility.

We're actually in the process of migrating all troubleshooting content from the devdocs site to the Help Center. PWA content should follow the same guidelines.

**Comment by zetlen** [comment] 2019-10-03 22:58
We need to add this stuff to the docs:

- Using `build:dev` to make uncompressed bundles, to debug things you can't reproduce in dev mode
- Using the `DEBUG` environment variable to control the logging by the [debug library](http://npmjs.com/package/debug) used in our NodeJS tools
- Installing and using the React , Apollo, and GraphQL dev tools
- Using the GraphQL Playground

**Comment by jcalcaben** [comment] 2019-10-18 20:56
Created the following internal issues to move the current troubleshooting topics to the Magento Knowledge Base:

* KB-361
* KB-362
* KB-363
* KB-364
* KB-365

**Comment by jcalcaben** [comment] 2019-10-18 21:15
Created github issues for docs requested by @zetlen:

#1906
#1907
#1908

**Comment by jcalcaben** [comment] 2019-10-18 21:17
Closing this issue since there is nothing left to do for it. We will continue to monitor requests for troubleshooting and/or debugging topic and determine whether it should be in the KB or docs site.

**Closed by jcalcaben** 2019-10-18 21:17 UTC
Labels: documentation
