### ISSUE TITLE
[bug]: Filter delimiter is likely to fail under some circumstances

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#3748] opened 2022-04-01 10:56 UTC
**Describe the bug**

When you have a filter label that looks like "Audio, Video & Multimedia" the default delimiter "," is not going to work and it will send a part of the label to the backend instead of the attribute code.

**To reproduce**

1. Add an attribute to the filters with a comma in the label
2. Go to category page and click that new filter and note that it's not sending the attribute code in the filter variable to the backend

**Expected behavior**

It just works like other filters

**Possible solutions**

The easiest solution is to change the DELIMITER inside https://github.com/magento/pwa-studio/blob/551d9680b49236b76e9db69e3156cca5d99b0853/packages/peregrine/lib/talons/FilterModal/helpers.js#L1 to something else like ",," or "/" something that won't be used in a filter label

**Debug Report**

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: Windows
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: 
-   Magento Version [e.g Adobe Commerce 2.4]: 2.4.x

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by Jordaneisenburger** [comment] 2022-04-01 10:57
Please let me know what delimiter we should use and I can create a PR

@magento I am working on this

**Comment by glo80771** [comment] 2023-07-03 07:24
This issue is reproducible and hence confirming the issue.

**Comment by glo42707** [comment] 2023-07-06 11:50
@adobe export issue to JIRA project PWA as Bug

**Comment by glo42707** [comment] 2023-07-19 06:44
hey,

@Jordaneisenburger, after retesting by team, we are not able to reproduce it even as per given steps followed.
kindly let us know if we are missing anything to reproduce same. since Filter is working fine for custome attributes.
![image](https://github.com/magento/pwa-studio/assets/84493875/13bdcc8b-6c3f-4540-b208-85cb9ee6dca4)

**Comment by glo42707** [comment] 2023-08-16 17:26
closing this ticket since no reply from Reporter on Github Ticket from past 2 weeks as per defined process. please feel free to reopen in case still persisit.

**Closed** 2023-08-16 17:26 UTC
Labels: bug, Progress: done, Issue: Needs Update
