### ISSUE TITLE
[bug]: Category Image expands beyond Tile

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3089] opened 2021-03-28 07:04 UTC
**Describe the bug**

This particular image extends beyond the bounds of its tile on the Category page.

**To reproduce**

1. Upload this specific image as a product image
1. Navigate to the Category page that displays this product
1. See that this image extends beyond the bounds of the tile and overlaps product name and price information

**Expected behavior**

Image remains constrained appropriately.

**Screenshots**

<img width="183" alt="Screenshot 2021-03-28 at 9 58 22" src="https://user-images.githubusercontent.com/14073311/112744907-b7755900-8fac-11eb-9e83-b383fc62adae.png"]

**Possible solutions**

It only happens in category. The same image in product is fine.

I am also attaching the exact image in question here (in case there is a specific problem with the image):

!https://user-images.githubusercontent.com/14073311/112744932-f3a8b980-8fac-11eb-85a5-25772213fbdb.jpeg!

**Please let us know what packages this bug is in regards to:**
 - [ ] `venia-concept`
 - [x] `venia-ui`
 - [ ] `pwa-buildpack`
 - [ ] `peregrine`
 - [ ] `pwa-devdocs`
 - [ ] `upward-js`
 - [ ] `upward-spec`
 - [ > `create-pwa`

**Comment by sirugh** [comment] 2021-03-28 12:55
@magento export issue to JIRA project PWA as Bug

**Comment by supernova-at** [comment] 2021-04-06 18:20
Hi @plamenh , thank you for reporting this issue and including the original image.

We cannot reproduce the black rectangle but this image does incorrectly exceed the bounds of the category tile:
![Screen Shot 2021-04-06 at 1 16 42 PM](https://user-images.githubusercontent.com/13182778/113759354-98787480-96da-11eb-968f-4efc2c041335.png)

I have repurposed the corresponding JIRA ticket to investigate why this might be the case.

**Comment by Tarun50745** [comment] 2023-07-16 12:24
Followed below mentioned steps,

1. Added a new product with ( tyre ) image as mentioned in description.
2. Navigated to relevant category to see the newly added product.

**Result**: Found image is appearing within the its tiles, no overlap issue exists.
Below are the screenshots attached .

<img width="1464" alt="Screenshot 2023-07-16 at 5 48 44 PM" src="https://github.com/magento/pwa-studio/assets/127731581/4623aa0e-dab3-468d-9792-0c7edbbde35b">
<img width="1440" alt="Screenshot 2023-07-16 at 5 48 54 PM" src="https://github.com/magento/pwa-studio/assets/127731581/1a60a2e0-f51d-45fd-94ea-31cf4b68defd">
<img width="723" alt="Screenshot 2023-07-16 at 5 51 14 PM" src="https://github.com/magento/pwa-studio/assets/127731581/129e3b3f-f1ba-4aa2-83bf-89774d6d43f4">

**Comment by glo42707** [comment] 2023-08-04 12:06
closing the ticket since no updates from past 2 week as per defined process.
Please freel free to reopen the issue in case still persist.

**Closed by glo42707** 2023-08-04 12:06 UTC
Labels: bug, Issue: Needs Update, issue: Cannot Reproduce
