### ISSUE TITLE
PWA server ready url not working in browser

### ISSUE THREAD

**Issue by iovistainc** [magento/pwa-studio#4192] opened 2023-11-01 08:42 UTC
PWADevServer ready at                                  
  https://pwamagento45-jifxf.local.pwadev:8697/
  
  Hello,
  I am using ubuntu and PWA installation successfully but the URL not working in browser,
It gives below errors.
This site can’t be reachedCheck if there is a typo in pwamagento45-jifxf.local.pwadev.
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/magento/pwa-studio/assets/16300151/5286f027-2150-4f3e-86cf-96fa1a487e37)
![image](https://github.com/magento/pwa-studio/assets/16300151/669dc947-62bd-4bfc-839b-53fb4cd3676c)

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Please let us know what packages this bug is in regards to:**

-   [ ] `pwa-devdocs`
-   [ ] `create-pwa`

**Comment by glo82145** [comment] 2024-05-08 10:48
[@adobe](https://github.com/adobe) export issue to Jira project PWA

**Comment by glo82145** [comment] 2024-05-09 09:07
@adobe export issue to Jira project PWA

**Comment by glo85315** [comment] 2024-07-25 07:26
HI @iovistainc ,
Following our recent investigation into the issue you reported, we regret to inform you that we were unable to reproduce the problem on our end.please find attached video

Uploading PWA-3275.mov…

**Comment by glo85315** [comment] 2024-07-25 07:26
https://github.com/user-attachments/assets/53197b9e-9998-4ba2-abab-4813495f9be9

**Comment by glo42707** [comment] 2024-08-08 07:50
as per internal PWA process, closing this ticket since no responce from report for more than 2 weeks.

**Closed** 2024-08-08 07:49 UTC
Labels: bug, Progress: done
