### ISSUE TITLE
[doc]: Documentation instructions for deploying to aws

### ISSUE THREAD

**Issue by threescs** [magento/pwa-studio#1402] opened 2019-06-28 08:37 UTC
Hello pwa-studio developer, I want to know how to deploy to aws, I need such a document description, thank you

**Comment by threescs** [comment] 2019-06-28 09:32
The development environment will randomly generate a definable domain name and port, then how do I open the production environment to configure to aws

**Comment by threescs** [comment] 2019-06-28 10:39
https://venia-git-develop.magento-research1.now.sh/

I found the Venia storefront, I really want to know how it was deployed. I really want to ask, thank you. Thank you.

**Comment by jcalcaben** [comment] 2019-08-15 19:34
Closing as a duplicate of #1553

**Closed by jcalcaben** 2019-08-15 19:34 UTC
Labels: Progress: dev in progress, documentation
