### ISSUE TITLE
[bug]: Error on build:dev 

### ISSUE THREAD

**Issue by papiliond** [magento/pwa-studio#2901] opened 2020-12-07 16:40 UTC
**Describe the bug**
Running the `build:dev` script gives the following output:

```
$ yarn run clean && webpack --no-progress --env.mode development
$ rimraf dist
Emitting no ServiceWorker in development mode.
/home/itg/Repos/pwa-studio/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:219
                  throw createError(
                  ^

Error: [React Refresh] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly.
    at createError (/home/itg/Repos/pwa-studio/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/utils/createError.js:7:10)
    at /home/itg/Repos/pwa-studio/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:219:25
    at SyncHook.eval [as call] (eval at create (/home/itg/Repos/pwa-studio/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:15:1)
    at SyncHook.lazyCompileHook (/home/itg/Repos/pwa-studio/node_modules/tapable/lib/Hook.js:154:20)
    at NormalModule.createLoaderContext (/home/itg/Repos/pwa-studio/node_modules/webpack/lib/NormalModule.js:233:40)
    at NormalModule.doBuild (/home/itg/Repos/pwa-studio/node_modules/webpack/lib/NormalModule.js:285:30)
    at NormalModule.build (/home/itg/Repos/pwa-studio/node_modules/webpack/lib/NormalModule.js:438:15)
    at Compilation.buildModule (/home/itg/Repos/pwa-studio/node_modules/webpack/lib/Compilation.js:702:10)
    at /home/itg/Repos/pwa-studio/node_modules/webpack/lib/Compilation.js:949:14
    at /home/itg/Repos/pwa-studio/node_modules/webpack/lib/NormalModuleFactory.js:409:6
    at /home/itg/Repos/pwa-studio/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/itg/Repos/pwa-studio/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/home/itg/Repos/pwa-studio/node_modules/tapable/lib/Hook.js:154:20)
    at /home/itg/Repos/pwa-studio/node_modules/webpack/lib/NormalModuleFactory.js:138:29
    at /home/itg/Repos/pwa-studio/node_modules/webpack/lib/NormalModuleFactory.js:346:9
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
```

**To reproduce**
1. Run `yarn build:dev`
2. See the output.

**Expected behavior**
When HMR isn't enabled on webpack, the `@pmmmwh/react-refresh-webpack-plugin` shouldn't be added to the webpack plugins. (See ths issue: https://github.com/webpack/webpack/issues/1151)

**Possible solutions**

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
 - OS [e.g. iOS8.1, Windows 10]: Ubuntu 20.04.1 LTS
 - PWA Studio Version: 8.0.0
 - NPM version `npm -v`: 10.14.1
 - Node Version `node -v`: 10.14.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by fooman** [comment] 2020-12-08 02:03
looks like https://github.com/magento/pwa-studio/issues/2689

**Comment by sirugh** [comment] 2021-02-01 18:30
Closing as duplicate of #2689. Thanks for reporting!

**Closed by sirugh** 2021-02-01 18:30 UTC
Labels: Progress: ready for grooming, bug
