### ISSUE TITLE
[bug]: No product is shown until I sort by price instead of best match

### ISSUE THREAD

**Issue by drc0** [magento/pwa-studio#2537] opened 2020-07-08 17:00 UTC
**Describe the bug**
In the category page no product is shown until I sort by price instead of best match, don't know if is relevant bu I have multiple inventory sources, assigned to a custom "website stock", all products have quantities in those sources but not in the default one.

 - Magento Version: 2.3.5
 - PWA Studio Version: 6.0.1 (0837e212a81312473f365cd17d4ff7530ed2ce15)

**Comment by awilcoxa** [comment] 2020-07-13 17:27
Created PWA-747 in backlog for grooming

**Comment by tjwiebell** [comment] 2020-07-14 14:15
@drc0 - The sort component in PWA hard-codes what is presently the `product` query default `sort: {relevance: "DESC"}`, so I suspect that even just a `products` query with no sort input would give you the same output. I'm feeling like this is going to be an issue with GraphQL and MSI, but happy to help debug so we can help them isolate the root cause.

I replicated your setup, and while I struggled through learning some MSI lingo, I was able to get a "Website Stock" Stock set up with multiple sources (avoided using default), and was unable to reproduce on latest `develop`. I don't recall any bug fixes related to sorting, but its possible this was addressed already.

Could you try testing against `develop` to confirm this bug still exists? If it does, can you provide additional detail about your catalog setup, or provide the graphql endpoint to the instance?

**Comment by drc0** [comment] 2020-07-22 09:05
@tjwiebell Yes was testing against develop. Anyway that could be some sort of caching issue, I realized that from a different browser the issue was not there, I should dig how I'm supposed to clear the client/graphql cache maybe?

**Comment by tjwiebell** [comment] 2020-07-27 18:25
@drc0 - Ideally we should be making better use of `cache-and-network` fetch policies, but for development purposes to manually clear all caches in Chrome: Dev Tools > Application Tab > Clear storage > Clear site data.

I am going to close this issue out as not a bug, but please let me know if you continue to experience any problems.

**Closed by tjwiebell** 2020-07-27 18:25 UTC
Labels: bug
